#working port
#server:
#  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vitaly
    password: 070809
#datasource:
#url: jdbc:postgresql://temp-local-db/postgres
#username: postgres
#password: postgres
jpa:
hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create
show-sql: true
format_sql: true

server:
  servlet:
    encoding:
      force-response: true
      force: true

